#!/usr/bin/env python3
"""gen_asset_tables.py - the 3DS port's native asset list and ROM->asset map, from MM's spec.

The port compiles MM's assets (objects, scenes, rooms, interface, misc, text) natively for the 3DS (little-endian,
3DS pointers) and serves the game's ROM reads inside those segments from the compiled data instead of the
big-endian ROM (port/src/dma_shim.c, gVromMap). In MM every such segment is exactly one source file, so:
  port/asset_srcs.mk          ASSET_SRCS: every asset segment's .c (extracted, committed or generated)
  port/src_gen/vrom_map.c     { _<seg>SegmentRomStart, _<seg>SegmentRomEnd, port_seg_<seg> } per segment
Makefile.3ds compiles each asset file with port/include/port_asset_start.h first, which declares the zero-size
marker port_seg_<seg> ahead of all of the file's data; with declaration order kept (-fno-toplevel-reorder) and all
data in .data (-Dconst=, -fno-zero-initialized-in-bss) the marker is the segment's offset 0.
Left out: the Yaz0 archives (*_yar: the game decompresses them itself, so they stay ROM bytes) and the audio
segments (Audiobank/Audioseq/Audiotable, served from the ROM like the OoT port's).

usage: tools/port/gen_asset_tables.py   (after `make` has extracted the assets)
"""
import os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
VERSION = "n64-us"
ROOTS = ("extracted/%s" % VERSION, ".", "build/%s" % VERSION)
KINDS = ("objects", "scenes", "interface", "misc", "text")


def main():
    spec = open(os.path.join(REPO, "spec/spec")).read()
    rom = set(re.findall(r"^_(\w+)SegmentRomStart = ", open(os.path.join(REPO, "port/rom_symbols.ld")).read(), re.M))
    segs, missing = [], []
    for body in re.findall(r"beginseg(.*?)endseg", spec, re.S):
        name = re.search(r'name\s+"([^"]+)"', body).group(1)
        inc = re.findall(r'include\s+"\$\(BUILD_DIR\)/([^"]+)\.o"', body)
        if len(inc) != 1 or not inc[0].startswith("assets/") or inc[0].split("/")[1] not in KINDS:
            continue
        if os.path.basename(inc[0]) != name or name not in rom:
            missing.append(name)
            continue
        src = next((os.path.join(r, inc[0] + ".c") for r in ROOTS
                    if os.path.exists(os.path.join(REPO, r, inc[0] + ".c"))), None)
        if src is None:
            missing.append(name)
            continue
        segs.append((name, os.path.normpath(src)))
    with open(os.path.join(REPO, "port/asset_srcs.mk"), "w") as f:
        f.write("# generated by tools/port/gen_asset_tables.py - do not edit\nASSET_SRCS := \\\n")
        f.write(" \\\n".join("  " + src for _, src in segs) + "\n")
    with open(os.path.join(REPO, "port/src_gen/vrom_map.c"), "w") as f:
        f.write("/* generated by tools/port/gen_asset_tables.py - do not edit */\n")
        f.write("typedef struct { void* romStart; void* romEnd; void* native; } VromMapEntry;\n")
        f.write('#include "PR/ultratypes.h"\n#include "3ds_segment_consts.h"\n\n')
        for name, _ in segs:
            f.write("extern char port_seg_%s[];\n" % name)
        f.write("\nVromMapEntry gVromMap[] = {\n")
        for name, _ in segs:
            f.write("    { _%sSegmentRomStart, _%sSegmentRomEnd, port_seg_%s },\n" % (name, name, name))
        f.write("};\nu32 gVromMapCount = sizeof(gVromMap) / sizeof(gVromMap[0]);\n")
    print("%d asset segments -> port/asset_srcs.mk, port/src_gen/vrom_map.c; skipped: %s" % (len(segs), missing))


if __name__ == "__main__":
    sys.exit(main())
