#!/usr/bin/env python3
"""gen_link_symbols.py - linker symbol tables the 3DS build takes from the matching N64 build.

  port/archive_symbols.ld   the textures inside MM's Yaz0 archives (*_yar: item icons, pause pages, Bombers'
                            Notebook...): the game decompresses an archive into a segment and refers to its textures
                            by those segment addresses (e.g. gItemIconBombTex = 0x08006000)
  port/audio_syms_stub.ld   the audio tables' sequence / soundfont / sample bank offsets and sizes

usage: tools/port/gen_link_symbols.py   (after `make`; needs mips-linux-gnu-nm)
"""
import glob, os, re, shutil, subprocess

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BUILD = os.path.join(REPO, "build/n64-us")


def nm(path):
    tool = shutil.which("mips-linux-gnu-nm") or shutil.which("mips64-elf-nm") or "nm"
    out = subprocess.run([tool, path], capture_output=True, text=True, check=True).stdout
    return [l.split() for l in out.splitlines() if len(l.split()) == 3]


def main():
    elf = {name: int(val, 16) for val, _, name in nm(os.path.join(BUILD, "mm-n64-us.elf"))}
    names = sorted({n for o in glob.glob(os.path.join(BUILD, "assets/archives/*/*.symbols.o")) for _, _, n in nm(o)})
    with open(os.path.join(REPO, "port/archive_symbols.ld"), "w") as f:
        f.write("/* generated by tools/port/gen_link_symbols.py: textures inside the Yaz0 archives, at their segment\n"
                " * addresses (from the N64 build) */\n")
        for n in names:
            if n in elf:
                f.write("%s = 0x%08x;\n" % (n, elf[n]))
    audio = sorted(n for n in elf if re.match(r"(Sequence|Soundfont|SampleBank)_\d+_(Start|Size)$", n))
    with open(os.path.join(REPO, "port/audio_syms_stub.ld"), "w") as f:
        f.write("/* generated by tools/port/gen_link_symbols.py: audio table offsets and sizes (from the N64 build) */\n")
        for n in audio:
            f.write("%s = 0x%08x;\n" % (n, elf[n]))
    print("%d archive symbols, %d audio symbols" % (len(names), len(audio)))


if __name__ == "__main__":
    main()
