#!/usr/bin/env python3
"""gen_segment_tables.py - the 3DS port's N64 segment address tables, from the matching N64 build's ELF.

The game refers to ROM segments through linker symbols (_<name>SegmentRomStart, ...Start, ...TextEnd, ...). The 3DS
build links the game natively, so those N64 addresses come from the N64 build instead:
  port/rom_symbols.ld                  symbol assignments for the linker (ROM, text, data, bss, overlay bounds)
  port/include/3ds_segment_consts.h    the same values as relocation-free constants, plus the derived sizes

usage: tools/port/gen_segment_tables.py [build/n64-us/mm-n64-us.elf]   (after `make`; needs mips-linux-gnu-nm)
"""
import os, re, shutil, subprocess, sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
LD_KINDS = ("BssEnd", "BssStart", "DataEnd", "DataStart", "End", "OvlEnd", "OvlStart", "RomEnd", "RomStart", "Start",
            "TextEnd", "TextStart")
H_KINDS = LD_KINDS + ("RoDataEnd", "RoDataStart")
SIZES = (("Bss", "BssStart", "BssEnd"), ("Data", "DataStart", "DataEnd"), ("Ovl", "OvlStart", "OvlEnd"),
         ("RoData", "RoDataStart", "RoDataEnd"), ("Rom", "RomStart", "RomEnd"), ("Text", "TextStart", "TextEnd"))


def main():
    elf = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO, "build/n64-us/mm-n64-us.elf")
    nm = shutil.which("mips-linux-gnu-nm") or shutil.which("mips64-elf-nm") or "nm"
    out = subprocess.run([nm, elf], capture_output=True, text=True, check=True).stdout
    seg = {}
    for line in out.splitlines():
        m = re.match(r"([0-9a-fA-F]{8})\s+\S\s+_(\w+?)Segment(\w+)$", line)
        if m and m.group(3) in H_KINDS:
            seg.setdefault(m.group(2), {})[m.group(3)] = int(m.group(1), 16)
    names = sorted(seg)
    with open(os.path.join(REPO, "port/rom_symbols.ld"), "w") as f:
        for n in names:
            s = seg[n]
            for k in LD_KINDS:
                if k.startswith("Ovl") and s.get("OvlStart") == s.get("OvlEnd"):
                    continue  # not an overlay (no relocations)
                if k in s:
                    f.write("_%sSegment%s = 0x%08x;\n" % (n, k, s[k]))
    with open(os.path.join(REPO, "port/include/3ds_segment_consts.h"), "w") as f:
        f.write("#ifndef PORT_3DS_SEGMENT_CONSTS_H\n#define PORT_3DS_SEGMENT_CONSTS_H\n")
        f.write("/* generated by tools/port/gen_segment_tables.py: N64 segment symbols as relocation-free constants */\n")
        for n in names:
            s = seg[n]
            vals = dict(s)
            for size, a, b in SIZES:
                if a in s and b in s:
                    vals[size + "Size"] = s[b] - s[a]
            for k in sorted(vals):
                if k.startswith("Ovl") and s.get("OvlStart") == s.get("OvlEnd"):
                    continue
                f.write("#define _%sSegment%s ((u8*)0x%08xu)\n" % (n, k, vals[k] & 0xFFFFFFFF))
        f.write("#endif\n")
    print("%d segments -> port/rom_symbols.ld, port/include/3ds_segment_consts.h" % len(names))


if __name__ == "__main__":
    main()
