#!/usr/bin/env python3
"""gen_sequence_font_table.py - gSequenceFontTable for the 3DS build (port/src_gen/sequence_font_table_data.c).

The table (which soundfonts each sequence uses) is built by the decompilation as assembly data (.rodata). It starts with one
u16 offset per sequence (big-endian on the N64), then the font lists (bytes). The game reads the offsets as native
u16, so on the little-endian 3DS they are stored byte-swapped; without that every sequence finds font 0xFF and plays
silent (found on the OoT port). The first offset is the size of the offset section.

usage: tools/port/gen_sequence_font_table.py   (after `make`; needs mips-linux-gnu-objcopy)
"""
import os, shutil, subprocess, tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OBJ = os.path.join(REPO, "build/n64-us/assets/audio/sequence_font_table.o")


def main():
    objcopy = shutil.which("mips-linux-gnu-objcopy") or "objcopy"
    with tempfile.NamedTemporaryFile(suffix=".bin") as t:
        subprocess.run([objcopy, "-O", "binary", "-j", ".rodata", OBJ, t.name], check=True)
        data = bytearray(open(t.name, "rb").read())
    header = (data[0] << 8) | data[1]
    assert 0 < header <= len(data) and header % 2 == 0, header
    for i in range(0, header, 2):
        data[i], data[i + 1] = data[i + 1], data[i]
    lines = ["/* generated by tools/port/gen_sequence_font_table.py - do not edit: the first %d bytes (%d sequence"
             " offsets) are little-endian u16, the font lists bytes */" % (header, header // 2),
             "const unsigned char gSequenceFontTable[] __attribute__((aligned(2))) = {"]
    for i in range(0, len(data), 12):
        lines.append("  " + ", ".join("0x%02x" % b for b in data[i:i + 12]) + ",")
    lines.append("};")
    open(os.path.join(REPO, "port/src_gen/sequence_font_table_data.c"), "w").write("\n".join(lines) + "\n")
    print("gSequenceFontTable: %d bytes, %d sequences" % (len(data), header // 2))


if __name__ == "__main__":
    main()
