/* generated by tools/port/gen_u32_asset_ranges.py - asset arrays emitted as u32[] (texel/TLUT
 * bytes at address ^ 3 on the little-endian build, not ^ 7 like u64[] assets) */
#include "port_u32_assets.h"

extern const unsigned int gHylianYoungWomanBrownHairFaceTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanBrownHairSkinTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanBrownHairTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanDressNeckTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanDressTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanHandTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanSkinTex[] __attribute__((weak));
extern const unsigned int gHylianYoungWomanTLUT[] __attribute__((weak));
extern const unsigned int sObjJgameLightCorrectTex[] __attribute__((weak));
extern const unsigned int sObjJgameLightIncorrectTex[] __attribute__((weak));

const PortU32Asset gPortU32Assets[] = {
    { gHylianYoungWomanBrownHairFaceTex, 144 },
    { gHylianYoungWomanBrownHairSkinTex, 72 },
    { gHylianYoungWomanBrownHairTex, 72 },
    { gHylianYoungWomanDressNeckTex, 72 },
    { gHylianYoungWomanDressTex, 72 },
    { gHylianYoungWomanHandTex, 72 },
    { gHylianYoungWomanSkinTex, 72 },
    { gHylianYoungWomanTLUT, 576 },
    { sObjJgameLightCorrectTex, 576 },
    { sObjJgameLightIncorrectTex, 576 },
};
const int gPortU32AssetCount = 10;
