#ifndef SEGMENT_SYMBOLS_H
#define SEGMENT_SYMBOLS_H

/* PORT OVERRIDE for 3DS (from the OoT 3DS port): the original declares segment markers as extern symbols
 * (extern u8 _xSegmentStart[]). The 3DS build links the game natively, so the N64 addresses are baked in as
 * compile-time pointer constants (3ds_segment_consts.h, generated by tools/port/gen_segment_tables.py) and the
 * DECLARE_* macros are no-ops. Values are used for size arithmetic and as opaque overlay tokens (never
 * dereferenced). The SEGMENT_* helpers are MM's own (include/segment_symbols.h). */

#include "stddef.h"
#include "stdint.h"
#include "PR/ultratypes.h"

#include "romfile.h"
#include "3ds_segment_consts.h"

#define DECLARE_SEGMENT(name)
#define DECLARE_ROM_SEGMENT(name)
#define DECLARE_BSS_SEGMENT(name)
#define DECLARE_OVERLAY_SEGMENT(name)

#define SEGMENT_START(segment) (_ ## segment ## SegmentStart)
#define SEGMENT_END(segment) (_ ## segment ## SegmentEnd)
#define SEGMENT_SIZE(segment) ((uintptr_t)SEGMENT_END(segment) - (uintptr_t)SEGMENT_START(segment))

#define SEGMENT_ROM_START(segment) ((uintptr_t) _ ## segment ## SegmentRomStart)
#define SEGMENT_ROM_START_OFFSET(segment, offset) ((uintptr_t) (( _ ## segment ## SegmentRomStart ) + (offset)))
#define SEGMENT_ROM_END(segment) ((uintptr_t) _ ## segment ## SegmentRomEnd)
#define SEGMENT_ROM_SIZE(segment) (SEGMENT_ROM_END(segment) - SEGMENT_ROM_START(segment))
#define SEGMENT_ROM_SIZE_ALT(segment) ((size_t)( _ ## segment ## SegmentRomEnd - _ ## segment ## SegmentRomStart ))

#define SEGMENT_BSS_START(segment) (_ ## segment ## SegmentBssStart)
#define SEGMENT_BSS_END(segment) (_ ## segment ## SegmentBssEnd)
#define SEGMENT_BSS_SIZE(segment) ((uintptr_t)SEGMENT_BSS_END(segment) - (uintptr_t)SEGMENT_BSS_START(segment))

#endif
